version: "2.1"

services:
  client:
    depends_on:
      db:
        condition: service_healthy
    build: ./
    image: pokemon
    container_name: pokemon-client
    environment:
      # DB_HOST can also just be 'db'
      DB_HOST: pokemon-db
      DB_NAME: pokemon?characterEncoding=utf8
      DB_USER: vartanbeno
      DB_PASS: password
    ports:
      - "8080:8080"

  db:
    image: mysql:8
    container_name: pokemon-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: vartanbeno
      MYSQL_PASSWORD: password
    volumes:
      - "./data:/var/lib/mysql:rw"
      - "./mysql-init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
      interval: 15s
      retries: 6
