version: '3'

services:
  mysql-dev:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: vartanbeno
      MYSQL_PASSWORD: password
    volumes:
      - "./data:/var/lib/mysql:rw"
    ports:
      - "3308:3306"

  client:
    image: mysql:8
    container_name: client
    depends_on:
      - mysql-dev
    command: mysql -uvartanbeno -ppassword -hmysql-dev pokemon

